name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change this to your default branch if it's not main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Or your project's Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build # Or your project's build command

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Change this if your build output directory is different
          publish_branch: gh-pages # The branch where the deployed site will be hosted